---
- name: "Gather ec2 facts"
  ec2_metadata_facts:
  tags: push

- name: "Install Python3 and Docker dependencies on host"
  apt:
    name:
      - python3-apt
      - python3-docker
      - python3-boto3
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes
  tags: setup

- name: "Add Docker repo key to apt"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  tags: setup

- name: "Add docker repo to apt"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    filename: docker
    state: present
    update_cache: yes
  tags: setup

- name: "Install Docker"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
    state: present
    update_cache: yes
  tags: setup

- name: "Create Jenkins user"
  user:
    name: jenkins
    append: yes
    groups:
      - docker
  tags: setup

- name: "Systemd enable docker"
  systemd:
    name: docker
    enabled: yes
    state: reloaded
  tags: setup

- name: "Fetch Hadolint docker image"
  docker_image:
    name: hadolint/hadolint
    source: pull
  tags: setup

- name: "Build microblog docker image"
  docker_image:
    name: microblog
    tag: latest
    source: build
    state: present
    build:
      path: ../
      pull: yes
  tags: build

- name: "Request temporary credentials"
  sts_session_token:
  register: session_creds
  tags: push

- name: "Create ECR repository"
  ecs_ecr:
    aws_access_key: "{{ session_creds.sts_creds.access_key }}"
    aws_secret_key: "{{ session_creds.sts_creds.secret_key }}"
    security_token: "{{ session_creds.sts_creds.session_token }}"
    name: udacity/microblog
    state: present
    region: us-west-2
  tags: push