---
- name: "Install Docker"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - python3-docker
    state: present
    update_cache: yes
  tags: lint

- name: "Systemd enable docker"
  systemd:
    name: docker
    enabled: yes
    state: started
  tags: lint

- name: "Check if jenkins user exists"
  getent:
    database: passwd
    key: jenkins
    fail_key: no
  register: jenkins_user
  tags: lint

- name: "Add Jenkins user"
  user:
    name: jenkins
    append: yes
    groups:
      - docker
  when: not getent_passwd['jenkins']
  tags: lint

- name: "Fetch Hadolint docker image"
  docker_image:
    name: hadolint/hadolint
    source: pull
  tags: lint