---
- name: "Install Python3 and Docker dependencies on host"
  become: yes
  apt:
    name:
      - python3-apt
      - python3-docker
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes
  tags: lint

- name: "Add Docker repo key to apt"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  tags:lint
  
- name: "Add docker repo to apt"
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    filename: docker
    state: present
    update_cache: yes
  tags: lint

- name: "Install Docker"
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
    state: present
    update_cache: yes
  tags: lint

- name: "Systemd enable docker"
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started
  tags: lint

- name: "Check if jenkins user exists"
  getent:
    database: passwd
    key: jenkins
    fail_key: no
  register: jenkins_user
  tags: lint

- name: "Add Jenkins user"
  become: yes
  user:
    name: jenkins
    append: yes
    groups:
      - docker
  when: not getent_passwd['jenkins']
  tags: lint

- name: "Fetch Hadolint docker image"
  become: yes
  docker_image:
    name: hadolint/hadolint
    source: pull
  tags: lint