---
- name: "Install Python3 and Docker dependencies on host"
  apt:
    name:
      - python3-apt
      - python3-docker
      - python3-boto3
      - golang-go
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes
  tags: setup

- name: "Add Docker repo key to apt"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  tags: setup

- name: "Add docker repo to apt"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    filename: docker
    state: present
    update_cache: yes
  tags: setup

- name: "Install Docker"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
    state: present
    update_cache: yes
  tags: setup

- name: "Create Jenkins group"
  group:
    name: jenkins
    state: present
  tags: setup

- name: "Create Jenkins user"
  user:
    name: jenkins
    append: yes
    groups:
      - docker
      - jenkins
  tags: setup

- name: "Systemd enable docker"
  systemd:
    name: docker
    enabled: yes
    state: reloaded
  tags: setup

- name: "Check if docker credential helper exists"
  stat:
    path: /usr/local/bin/docker-credential-ecr-login
  register: cred_helper
  tags: setup

- name: "Build amazon-ecr-credential-helper"
  become: yes
  become_user: jenkins
  shell:
    cmd: go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login
  when: cred_helper.stat.exists == 'false'
  tags: setup

- name: "Update facts"
  become: yes
  become_user: jenkins
  setup:
  tags: setup
  
- name: "Get EC2 metadata facts"
  ec2_metadata_facts:
  tags: setup

- name: "Install docker credential-helper"
  copy:
    src: "{{ ansible_user_dir }}/go/bin/docker-credential-ecr-login"
    dest: /usr/local/bin/docker-credential-ecr-login
    mode: '0755'
    remote_src: yes
  tags: setup

- name: "Create docker-credential-helper directory"
  file:
    path: "{{ ansible_user_dir }}/.docker"
    state: directory
    mode: '0755'
    owner: 'jenkins'
    group: 'jenkins'
  tags: setup

- name: "Write docker-credential-helper config file"
  become: yes
  become_user: jenkins
  copy:
    content: '{ "credsStore": "ecr-login" }'
    dest: "{{ ansible_user_dir }}/.docker/config.json"
    mode: '0644'
    remote_src: yes
  tags: setup

- name: "Fetch Hadolint docker image"
  docker_image:
    name: hadolint/hadolint
    source: pull
  tags: setup

- name: "Build microblog docker image"
  docker_image:
    name: microblog
    tag: latest
    source: build
    state: present
    build:
      path: ../
      pull: yes
  tags: build

- name: "Request temporary credentials"
  sts_session_token:
    region: "{{ ansible_ec2_instance_identity_document_region }}"
  register: session_creds
  tags: build

- name: "Create ECR repository"
  ecs_ecr:
    aws_access_key: "{{ session_creds.sts_creds.access_key }}"
    aws_secret_key: "{{ session_creds.sts_creds.secret_key }}"
    security_token: "{{ session_creds.sts_creds.session_token }}"
    name: udacity/microblog
    state: present
    region: "{{ ansible_ec2_instance_identity_document_region }}"
  tags: build